# Generated by Django 3.2.4 on 2021-07-29 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedservice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 6, 58, 53, 580356, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
